### ISSUE TITLE
when i click on data to enter in a data page i have again a data link ?

### ISSUE THREAD

**Issue by vinber** [teritorio/clearance#11]
you add context on the top of a data pages, but there's always link to datas page ?

i don't know what to do

**Comment by vinber** [comment]
in small screen i didn't see data, only context !

![image](https://github.com/teritorio/clearance/assets/890869/7e711250-8986-4604-a79c-32e5562ab4ed)

**Comment by vinber** [comment]
completed it's different to "deployed" ?

**Comment by frodrigo** [comment]
> completed

The code is fixed.

> deployed

The software is deployed some where, by someone.
